### ISSUE TITLE
Does not work with Django 4.0

### ISSUE THREAD

**Issue by kegan** [svleeuwen/sortedm2m-filter-horizontal-widget#16] opened 2021-12-15 07:29 UTC
The current version of the `sortedm2m-filter-horizontal-widget` does not work with `django 4.0`.

Here is the error when we try to execute `./manage.py runserver`.

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/kegan/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/kegan/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 115, in inner_run
    autoreload.raise_last_exception()
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/utils/module_loading.py", line 57, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/kegan/.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kegan/projects/indoorcms-pyramid3/location/admin.py", line 11, in <module>
    from sortedm2m_filter_horizontal_widget.forms import SortedFilteredSelectMultiple
  File "/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/sortedm2m_filter_horizontal_widget/forms.py", line 7, in <module>
    from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (/Users/kegan/.pyenv/versions/indoorcms-pyramid3/lib/python3.8/site-packages/django/utils/encoding.py)
```

**Comment by svleeuwen** [comment] 2021-12-15 08:48
@kegan thanks for the report. I won't be able to look into this any time soon. Feel free to create a PR for it.

**Comment by kegan** [comment] 2021-12-18 11:08
Hi @svleeuwen . I have created a pull request (https://github.com/svleeuwen/sortedm2m-filter-horizontal-widget/pull/17) to support Django 4.0 (minimum support is Django 3.0 now).

Hope you can merge and release this soon. 

Thank you!

**Comment by kegan** [comment] 2022-01-23 04:08
Hi @svleeuwen Any chance of merging this pull request?

**Comment by kegan** [comment] 2022-06-04 13:41
@svleeuwen My apology for the late reply. I have fixed the commits. Are you able to merge the pull request?

**Comment by compmonks** [comment] 2022-08-25 07:49
Hello, I just encountered the same issue and ended up here by searching for a fix. Any chance to see a new release soon? :)
I am using the current master: https://github.com/svleeuwen/sortedm2m-filter-horizontal-widget/commit/367ff0ac8497360167465c67484984af10a7ccbf with django 4.0 and python 3.10.6

PS: the issue is found at line 7 in forms.py: `from django.utils.encoding import force_text`

**Comment by svleeuwen** [comment] 2023-07-26 10:33
Finally merged and released. Thanks @kegan for your contribution.

**Closed as completed by svleeuwen** 2023-07-26 10:33 UTC
